### ISSUE TITLE
Null FragmentManager

### ISSUE THREAD

**Issue by leachad** [leachad/buuteeq-ponyhax#2]
Fragment Manager in MyAccount is not instantiated. Not sure how to approach this. Wanted to submit a bug to the group.
![capture](https://cloud.githubusercontent.com/assets/8375763/7117978/19399aa8-e1b1-11e4-9a6c-d7a285c0c0b1.JPG)

**Comment by Huyzy** [comment]
How did you reproduce this again?

**Comment by leachad** [comment]
It was the output of the stack trace when I selected "Account Details" in
the Navigation Drawer on the MyAccount activity.

On Mon, Apr 13, 2015 at 8:29 AM, Huyzy <notifications@github.com> wrote:

> How did you reproduce this again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leachad/buuteeq-ponyhax/issues/2#issuecomment-92402023>
> .
>



-- 

*Best,*

*Andy*

*--------------------------------Andrew Leach*
Professional Technician
Tacoma Public Schools ELL
253-571-1110
aleach@tacoma.k12.wa.us

**Comment by 61ue5peed** [comment]
@leachad how are you Andrew

**Comment by leachad** [comment]
@61ue5peed I'm good man! How about you?

**Comment by 61ue5peed** [comment]
I'm better then I deserve :) You in seattle?

**Comment by leachad** [comment]
Same here haha. Living in Tacoma, working in Issaquah for Costco Travel. My oldest daughter will be 2 in august and expected baby girl #2 any day now. I'm a lucky guy.

**Comment by 61ue5peed** [comment]
Wow thats awesome!!! Be blessed man!

**Comment by leachad** [comment]
You too sir!
